name: Test GitHub Release on Push

on:
  push:
    branches:
      - main

jobs:
  test-release:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“ Create dummy file
        run: echo "this is a dummy apk file" > dummy.apk

      - name: ğŸ“ Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          draft: true
          name: "Test Release"
          tag_name: "test-release-${{ github.run_number }}"
          files: ./dummy.apk
